id: P003089
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9272
  title: བདུད་རྩི་སྨན་གྱི་རྣམ་དབྱེ་ངོ་བོ་ནུས་མིང་རྒྱས་པར་བཤད་པ་དྲི་མེད་ཤེལ་ཕྲེང་།
  author: ''
  volumes:
    626b3466290043e5a7c4373920fcca98:
      image_group_id: I1KG9536
      title: ''
      volume_number: 1
      total_pages: 288
